[project]
name = "aurora"
version = "0.1.0"
description = "Stock instrument forecast and portfolio optimization"
authors = [
    {name = "KushalSuvan",email = "kushalsuvanjenamani@gmail.com"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
